language: php
php:
  - "5.5"
  - "5.4"
install:
  - composer install
  - composer dump-autoload -o
before_script:
  - mysql -e 'create database fixtures_tests;'
  - mysql -u root fixtures_tests < ./tests/Support/Scripts/create_fixtures_db.sql

